services:
  db:
    image: postgres:18.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'yukinu'
      POSTGRES_PASSWORD: 'supersecret'
      POSTGRES_DB: 'db'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U yukinu -d db']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  pg_data:
